version: '3.7'

services:
  app:
    image: ecency/api:latest
    environment:
      - PRIVATE_API_ADDR
      - PRIVATE_API_AUTH
      - HIVESIGNER_CLIENT_SECRET
      - SEARCH_API_ADDR
      - SEARCH_API_SECRET
      - REVUE_TOKEN
      - REDIS_URL
    ports:
      - "4000:4000"
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.9"
          memory: 2048M
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 5
        window: 60s
